# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Raschet.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Raschet(object):
    def setupUi(self, Raschet):
        Raschet.setObjectName("Raschet")
        Raschet.resize(288, 346)
        Raschet.setToolTipDuration(-1)
        self.text = QtWidgets.QLabel(Raschet)
        self.text.setGeometry(QtCore.QRect(10, 0, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.text_vvod = QtWidgets.QLabel(Raschet)
        self.text_vvod.setGeometry(QtCore.QRect(20, 30, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_vvod.setFont(font)
        self.text_vvod.setObjectName("text_vvod")
        self.line_vvod = QtWidgets.QTextEdit(Raschet)
        self.line_vvod.setGeometry(QtCore.QRect(20, 50, 241, 31))
        self.line_vvod.setObjectName("line_vvod")
        self.line_vvod.setToolTip("Английская раскладка")
        self.pb_shifr = QtWidgets.QPushButton(Raschet)
        self.pb_shifr.setGeometry(QtCore.QRect(20, 90, 241, 28))
        self.pb_shifr.setObjectName("pb_shifr")
        self.text_shifr = QtWidgets.QLabel(Raschet)
        self.text_shifr.setGeometry(QtCore.QRect(20, 140, 171, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_shifr.setFont(font)
        self.text_shifr.setObjectName("text_shifr")
        self.line_shifr = QtWidgets.QTextEdit(Raschet)
        self.line_shifr.setGeometry(QtCore.QRect(20, 160, 241, 31))
        self.line_shifr.setObjectName("line_shifr")
        self.pb_rashifr = QtWidgets.QPushButton(Raschet)
        self.pb_rashifr.setGeometry(QtCore.QRect(20, 200, 241, 28))
        self.pb_rashifr.setObjectName("pb_rashifr")
        self.line_enter = QtWidgets.QTextEdit(Raschet)
        self.line_enter.setGeometry(QtCore.QRect(20, 260, 241, 31))
        self.line_enter.setObjectName("line_enter")
        self.text_enter = QtWidgets.QLabel(Raschet)
        self.text_enter.setGeometry(QtCore.QRect(20, 240, 181, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_enter.setFont(font)
        self.text_enter.setObjectName("text_enter")
        self.exit = QtWidgets.QPushButton(Raschet)
        self.exit.setGeometry(QtCore.QRect(150, 310, 121, 28))
        self.exit.setObjectName("exit")

        self.retranslateUi(Raschet)
        self.exit.clicked.connect(Raschet.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Raschet)

    def retranslateUi(self, Raschet):
        _translate = QtCore.QCoreApplication.translate
        Raschet.setWindowTitle(_translate("Raschet", "Метод гаммирования"))
        self.text.setText(_translate("Raschet", "Заполните значения для ПСЧ:"))
        self.text_vvod.setText(_translate("Raschet", "Введите исходный текст:"))
        self.pb_shifr.setText(_translate("Raschet", "зашифравать"))
        self.text_shifr.setText(_translate("Raschet", "Зашифрованный текст:"))
        self.pb_rashifr.setText(_translate("Raschet", "Расшифровать"))
        self.text_enter.setText(_translate("Raschet", "Расшифрованный текст:"))
        self.exit.setText(_translate("Raschet", "Выход"))
